var images = [
['brewhousegallery','Brewhouse Gallery<br>Lake Park, FL<br>June 10, 2022'],
['pigeonkey','Pigeon Key, FL<br>April 1, 2022'],
['abitamystery','Abita Mystery House<br>Abita Springs, LA<br>December 31, 2021'],
['sundownsaloon','Sundown Saloon<br>Boulder, CO<br>December 26, 2021'],
['rockhall','Rock &amp; Roll Hall of Fame<br>Cleveland, OH<br>July 19, 2021'],
['idle','The Idle<br>Indianapolis, IN<br>July 15, 2021'],
['broadripple','Rainbow Bridge<br>Broad Ripple, IN<br>July 15, 2021'],
['burtreynolds','Burt Reynolds Park<br>Jupiter, FL<br>March 18, 2020'],
['jwakefield','J Wakefield Brewing<br>Miami, FL<br>February 6, 2020'],
['bbanjo','Bangin&rsquo; Banjo Brewing Company<br>Pompano Beach, FL<br>January 25, 2020'],
['chi66','Jackson Blvd &amp; Sangamon St<br>Chicago, IL<br>November 13, 2019'],
['marinestadium','Marine Stadium<br>Miami, FL<br>September 18, 2019'],
['tasteofmaine','Taste of Maine<br>Woolwich, ME<br>August 3, 2019'],
['a1a2','North Palm Beach, FL<br>June 4, 2019'],
['civilsociety','Civil Society<br>West Palm Beach, FL<br>June 2, 2019'],
['wendys','Wendy&rsquo;s<br>Jupiter, FL<br>March 22, 2019'],
['catos','Oakland, CA<br>March 2, 2019'],
['foodshack','Food Shack<br>Jupiter, FL<br>January 13, 2019'],
['macsclub','Mac&rsquo;s Club Deuce<br>Miami Beach, FL<br>December 26, 2018'],
['beertrade','Beer Trade Co<br>Delray Beach, FL<br>December 1, 2018'],
['brassring','The Brass Ring Pub<br>North Palm Beach, FL<br>November 27, 2018'],
['wynwood','Wynwood<br>Miami, FL<br>July 30, 2018'],
['umich','Denison Archway<br>University of Michigan<br>July 8, 2018'],
['lighthousecove','Lighthouse Cove Adventure Golf<br>Jupiter, FL<br>December 28, 2017'],
['niagara','Horseshoe Falls<br>Niagara Falls, Canada<br>November 13, 2017'],
['gramps','Gramps<br>Miami, FL<br>October 21, 2017'],
['folsomprison','Folsom Prison<br>Folsom, CA<br>August 27, 2017'],
['nimbusdam','Nimbus Dam<br>Gold River, CA<br>August 27, 2017'],
['vernoniamill','Old Saw Mill<br>Vernonia, OR<br>August 25, 2017'],
['banksvernonia','Banks-Vernonia State Trail<br>Vernonia, OR<br>August 25, 2017'],
['springwater','Springwater Corridor<br>Portland, OR<br>August 23, 2017'],
['squirescastle','Squire&rsquo;s Castle<br>Willoughby Hills, OH<br>July 15, 2017'],
['lakemichigan','Lake Michigan<br>Torch Lake Township, MI<br>July 2, 2017'],
['sidelinghill','Sideling Hill Tunnel<br>Abandoned Pennsylvania Turnpike<br>June 12, 2017'],
['shhs','Shaker Heights, OH<br>May 30, 2017'],
['lakemarion','Lake Marion<br>South Carolina<br>May 9, 2017'],
['birdhouse','Durham, NC<br>April 20, 2017'],
['pinhook','The Pinhook<br>Durham, NC<br>March 14, 2017'],
['hawriver','Haw River Bridge<br>Bynum, NC<br>February 19, 2017'],
['surfclub','Surf Club<br>Durham, NC<br>January 12, 2017'],
['fuelfuddle','Fuel and Fuddle<br>Pittsburgh, PA<br>November 29, 2016'],
['captaintonys','Captain Tony&rsquo;s<br>Key West, FL<br>October 16, 2016'],
['mile0','Mile 0<br>Key West, FL<br>October 15, 2016'],
['slipperynoodle','Slippery Noodle Inn<br>Indianapolis, IN<br>September 28, 2016'],
['buddysrun','Lansing, NC<br>September 18, 2016'],
['dutchboy','Dutch Boy Burger<br>Brooklyn, NY<br>June 26, 2016'],
['tinyhouse','Carrboro, NC<br>May 26, 2016'],
['station2','The Station<br>Carrboro, NC<br>May 15, 2016'],
['flattop','Flat Top Fire Tower<br>Blowing Rock, NC<br>March 26, 2016'],
['thecave','The Cave<br>Chapel Hill, NC<br>February 17, 2016'],
['greenman','Green Man Brewery<br>Asheville, NC<br>December 19, 2015'],
['amona','Telang Family Home<br>Amona, Goa, India<br>November 22, 2015'],
['mangueshi','Mangueshi Temple<br>Goa, India<br>November 22, 2015'],
['sjstudios','SJ Studios<br>Mumbai, India<br>November 17, 2015'],
['labocana','La Bocana<br>Playa El Tunco, El Salvador<br>September 6, 2015'],
['ikes','Ike&rsquo;s Place<br>San Francisco, CA<br>April 18, 2015'],
['a1a','A1A &amp; Indiantown<br>Jupiter, FL<br>October 29, 2014'],
['westashley','West Ashley Greenway<br>Charleston, SC<br>October 15, 2014'],
['attbridge','American Tobacco Trail Bridge<br>Durham, NC<br>October 1, 2014'],
['tompkinssquare','Tompkins Square Park<br>Manhattan, NY<br>June 29, 2014'],
['magnettheater','Magnet Theater<br>Manhattan, NY<br>June 28, 2014'],
['sushicruise','Sushi Cruise<br>Claremont, CA<br>April 5, 2014'],
['lasvegas', 'Tropicana Avenue<br>Las Vegas, NV<br>December 15, 2013'],
['cedarpoint', 'Cedar Point<br>Sandusky, OH<br>August 3, 2013'],
// ['copacabana', 'Copacabana, Bolivia<br>June 15, 2013'],
['adamstract', 'Adams Tract<br>Carrboro, NC<br>May 7, 2013'],
['zzyzxsign', 'CA I-15 &ndash; Exit 239<br>March 17, 2013'],
['fathersoffice', 'Father&rsquo;s Office<br>Santa Monica, CA<br>March 15, 2013'],
['butter', 'Butter<br>San Francisco, CA<br>March 13, 2013'],
['506', 'Local 506<br>Chapel Hill, NC<br>February 2, 2013'],
['southernrail', 'Southern Rail<br>Carrboro, NC<br>January 16, 2013'],
['willington', 'Willington, SC<br>November 22, 2012'],
['nightlight','Night Light<br>Chapel Hill, NC<br>November 5, 2012'],
['parthenon','Parthenon<br>Nashville, TN<br>October 5, 2012'],
['secondwind','Second Wind<br>Carrboro, NC<br>September 14, 2012'],
['piggly','Piggly Wiggly<br>Edisto, SC<br>August 21, 2012'],
['nortons','Norton Rat&rsquo;s Pub<br>Cusco, Peru<br>July 4, 2012'],
['ollantaytambo','Ollantaytambo<br>Peru<br>July 4, 2012'],
['qenqo','Qenqo<br>Cusco, Peru</br>July 2, 2012'],
['daves','Dave&rsquo;s Cosmic Subs<br>Cleveland Heights, OH<br>May 14, 2012'],
['station','The Station<br>Carrboro, NC<br>May 10, 2012'],
['carrboro','Carrboro, NC<br>May 2, 2012'],
['mudd','Pomona College &ndash; Mudd Dorm<br>Claremont, CA<br>Apr 29, 2012'],
['lindas','Linda&rsquo;s<br>Chapel Hill, NC<br>Apr 10, 2012'],
['highline','The High Line<br>Manhattan, NY<br>Dec 18, 2011'],
['jupiterinlet','Jupiter Inlet<br>Jupiter, FL<br>Nov 27, 2011'],
['keywest','Mile 0<br>Key West, FL<br>Nov 18, 2011'],
['duffys','Duffy&rsquo;s<br>Jupiter, FL<br>Nov 12, 2011'],
['outback','Outback<br>Jupiter, FL<br>Nov 4, 2011'],
['miamibeach','Miami Beach<br>Miami, FL<br>Sep 22, 2011'],
['squaregrouper','Square Grouper<br>Jupiter, FL<br>Sep 6, 2011'],
['bourbonst','Bourbon Street<br>New Orleans, LA<br>Aug 8, 2011'],
['pradamarfa','Prada Marfa<br> Valentine, TX<br>Aug 5, 2011'],
['greenwichsteps','Greenwich Steps<br>San Francisco, CA<br> Nov 24, 2010'],
['palazzo','Palazzo<br>Las Vegas, NV<br>Oct 17, 2010'],
['facebook','Facebook HQ &ndash; Building 6<br>Palo Alto, CA<br>Sep 28, 2010'],
['rosecrown','Rose and Crown<br>Palo Alto, CA<br>Jul 11, 2010'],
['stpeters','St. Peter&rsquo;s Square<br>Vatican City<br>Jul 3, 2010'],
['boboli','Boboli Gardens<br>Florence, Italy<br>Jun 29, 2010'],
['aquarius','Aquarius Theater<br>Palo Alto, CA<br>May 1, 2010'],
['fortmason','Fort Mason<br>San Francisco, CA<br>Apr 15, 2010'],
['twitter','Twitter HQ<br>San Francisco, CA<br>Mar 22, 2010'],
['fatangel','Fat Angel<br>San Francisco, CA<br>Mar 20, 2010'],
['nepenthe','Nepenthe<br>Big Sur, CA<br>Feb 13, 2010'],
['zzyzx','Zzyzx, CA<br>Oct 26, 2009'],
['lostlake','Lost Lake<br>San Bernardino, CA<br>Oct 26, 2009'],
['crifdogs','Crif Dogs<br>Manhattan, NY<br>Sep 25, 2009'],
['sutrobaths','Sutro Baths<br>San Francisco, CA<br>Aug 29, 2009'],
['500','500 Ocean Trail<br>Jupiter, FL<br>Jul 20, 2009'],
['publix','Publix<br>Jupiter, FL<br>Jul 19, 2009'],
['pebblebeach','Peter Hay Golf Course &ndash; Hole 4<br>Pebble Beach, CA<br>Jun 13, 2009'],
['lockspotcafe','Lockspot Cafe<br>Seattle, WA<br>May 25, 2009'],
['fremonttroll','Fremont Troll<br>Seattle, WA<br>May 25, 2009'],
['bottomhill','Bottom of the Hill<br>San Francisco, CA<br>May 9, 2009'],
['rinconisland','Rincon Island Causeway<br> Mussel Shoals, CA<br>May 8, 2009'],
['pyramidlake','Pyramid Lake, CA<br>May 7, 2009'],
['pomonabaseball','Pomona College Baseball Field<br>Claremont, CA<br>May 7, 2009'],
['pomonacarnegie','Pomona College &ndash; Carnegie Building<br>Claremont, CA<br>May 7, 2009']
];